# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: cd-resource-push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-ecr-push:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ECR_REGISTORY: ${{ secrets.AWS_ECR_REGISTORY }}
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: jar build
        run: gradle clean build
      - name: image build
        run: docker build -t ${{ env.AWS_ECR_REGISTORY }}/${{ env.AWS_ECR_REPOSITORY }}:latest .
      - name: aws-credential-setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: image push
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ECR_REGISTORY }}
          docker push ${{ env.AWS_ECR_REGISTORY }}/${{ env.AWS_ECR_REPOSITORY }}:latest

  application-meta-push:
    needs: build-and-ecr-push
    runs-on: ubuntu-latest
    env:
      NET_API_USERNAME: ${{ secrets.NET_API_USERNAME }}
      NET_API_PASSWORD: ${{ secrets.NET_API_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: application-meta push
        run: |
          token=`curl -X POST -d email=${{ env.NET_API_USERNAME }} -d password=${{ env.NET_API_PASSWORD }} https://api.ningenme.net/v1/login -i | grep MeCookie | awk -F '=|;' '{print $2}'`
          curl -X POST -b "MeCookie=${token}" -H "Content-Type: application/json" https://api.ningenme.net/v1/application-metas/net-batch
